//Executar
//Exemplo.Executar();
Atividade1.Executar();
//Atividade2.Executar();
//Atividade3.Executar();
//Atividade4.Executar();
//Atividade5.Executar();
//Atividade6Executar();
//Atividade7Executar();
//Atividade8Executar();
//Atividade9Executar